### ISSUE TITLE
How to prepare 'channels' Information?

### ISSUE THREAD

**Issue by maihao14** [wayneweiqiang/PhaseNet#4]
Dear Prof.Zhu,
I appreciate that you provide such a powerful DL Phase Pick method.  Reccent days I am trying some earthquake data with Phase Net. However, I am not sure how to record 'channels' names in csv.  Does PhaseNet only accept certain E N Z channels names?  Or it doesn't matter which types of text names data has?  I appreciate your answers.

**Comment by HaiNanJim** [comment]
随便给3个名字用下划线分割就好了，代码里也是只检测用下划线可以分割成几部分

**Comment by wayneweiqiang** [comment]
Hi,

For prediction on numpy format, you actually did not need the "channel" column. The numpy array should contain E,N,Z channels in order. The "channel" information is used during training when I apply augmentation to stack data from the same channels.

For prediction on mseed format, you need to tell the channel names in your mseed files by adding them to the csv file under "E, N, Z" columns, so that the data_reader.py will extract the data based on the provided channel names from the mseed file.

Best,
Weiqiang
